# Generated by Django 5.2.1 on 2025-05-21 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_mesa', models.CharField(help_text="Ej: 'Mesa 1', 'Barra 2'", max_length=10, unique=True)),
                ('capacidad', models.PositiveIntegerField(default=1)),
                ('ubicacion', models.CharField(blank=True, help_text="Ej: 'Salón Principal', 'Terraza'", max_length=100, null=True)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('ocupada', 'Ocupada'), ('reservada', 'Reservada')], default='disponible', max_length=20)),
                ('venta_actual', models.ForeignKey(blank=True, help_text='Venta activa asociada a esta mesa si está ocupada.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mesa_asignada', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
                'ordering': ['ubicacion', 'numero_mesa'],
            },
        ),
    ]
