"""
Django settings for restaurante_core project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os # Importar os para leer variables de entorno
from django.core.exceptions import ImproperlyConfigured # Para errores de configuración

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Intenta leer la SECRET_KEY de una variable de entorno.
# Si no se encuentra, usa una clave por defecto (SOLO PARA DESARROLLO).
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-w5sx5nz*x6*jxrt=z-jv8w5xh9#iw&7wg_5!dcuvrbilb$=%++')

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG se establece a False si DJANGO_ENV es 'production' o si DEBUG_APP es 'False'.
# Por defecto, True para desarrollo.
DEBUG_APP_ENV = os.environ.get('DEBUG_APP', 'True').lower()
if DEBUG_APP_ENV not in ['true', 'false']:
    raise ImproperlyConfigured("La variable de entorno DEBUG_APP debe ser 'True' o 'False'.")
DEBUG = DEBUG_APP_ENV == 'true'

if os.environ.get('DJANGO_ENV') == 'production':
    DEBUG = False
    if SECRET_KEY == 'django-insecure-w5sx5nz*x6*jxrt=z-jv8w5xh9#iw&7wg_5!dcuvrbilb$=%++':
        raise ImproperlyConfigured("LA SECRET_KEY POR DEFECTO NO DEBE USARSE EN PRODUCCIÓN.")

# ALLOWED_HOSTS: Configurar con los dominios/IPs permitidos en producción.
# Puede leerse de una variable de entorno como una cadena separada por comas.
# Ejemplo: DJANGO_ALLOWED_HOSTS="localhost,127.0.0.1,mi_dominio.com"
ALLOWED_HOSTS_ENV = os.environ.get('DJANGO_ALLOWED_HOSTS')
if ALLOWED_HOSTS_ENV:
    ALLOWED_HOSTS = ALLOWED_HOSTS_ENV.split(',')
else:
    ALLOWED_HOSTS = [] # Dejar vacío para desarrollo local si no se define la variable

# Si DEBUG es False y ALLOWED_HOSTS está vacío, Django no se ejecutará.
# Es útil tener un host por defecto para desarrollo si DEBUG es True y la variable no está seteada.
if DEBUG and not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'stock',
    'ventas',
    'gestion_mesas',
    'informes',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'restaurante_core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'restaurante_core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Configuración de Base de Datos
DB_ENGINE = os.environ.get('DB_ENGINE')
DB_NAME = os.environ.get('DB_NAME')
DB_USER = os.environ.get('DB_USER')
DB_PASSWORD = os.environ.get('DB_PASSWORD')
DB_HOST = os.environ.get('DB_HOST')
DB_PORT = os.environ.get('DB_PORT')

if DB_ENGINE and DB_NAME and DB_USER and DB_PASSWORD and DB_HOST and DB_PORT:
    # Configuración para PostgreSQL (o la base de datos de producción) usando variables de entorno
    DATABASES = {
        'default': {
            'ENGINE': DB_ENGINE,
            'NAME': DB_NAME,
            'USER': DB_USER,
            'PASSWORD': DB_PASSWORD,
            'HOST': DB_HOST,
            'PORT': DB_PORT,
        }
    }
else:
    # Configuración de SQLite para desarrollo si no se proporcionan variables de entorno de DB
    # (Advertencia: No usar SQLite en producción para esta aplicación)
    if os.environ.get('DJANGO_ENV') == 'production':
        raise ImproperlyConfigured("Las variables de entorno de la base de datos son requeridas en producción.")
    
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
    # Imprimir una advertencia si estamos en modo DEBUG pero no se detectaron variables de DB
    # Esto es más una advertencia para el desarrollador, no para producción.
    if DEBUG:
        print("ADVERTENCIA: No se detectaron variables de entorno para la base de datos. Usando SQLite por defecto para desarrollo.")


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# STATIC_ROOT: Directorio donde `collectstatic` reunirá todos los archivos estáticos para producción.
# Asegúrate de que este directorio sea servido por tu servidor web en producción.
STATIC_ROOT = BASE_DIR / 'staticfiles' 

# Opcional: STATICFILES_DIRS si tienes archivos estáticos fuera de las apps
# STATICFILES_DIRS = [
#     BASE_DIR / "static_globales", 
# ]


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Login/Logout settings
LOGIN_URL = 'login' # Nombre de la URL de login
LOGIN_REDIRECT_URL = 'home' # Nombre de la URL a la que se redirige después del login exitoso
# LOGOUT_REDIRECT_URL = 'home' # Ya se configuró en urls.py, pero puede definirse aquí también si se usa django.contrib.auth.urls directamente


# CSRF y Security (ejemplos, ajustar según necesidad en producción)
# if not DEBUG: # Configuraciones específicas para producción
#     CSRF_COOKIE_SECURE = True
#     SESSION_COOKIE_SECURE = True
#     SECURE_SSL_REDIRECT = True # Si tu sitio usa HTTPS
#     SECURE_HSTS_SECONDS = 31536000 # 1 año
#     SECURE_HSTS_INCLUDE_SUBDOMAINS = True
#     SECURE_HSTS_PRELOAD = True
#     SECURE_BROWSER_XSS_FILTER = True
#     SECURE_CONTENT_TYPE_NOSNIFF = True
#     # X_FRAME_OPTIONS = 'DENY' # Ya está en MIDDLEWARE por defecto
